### PR TITLE
Fixing problem when is radio button and no has selected button.

### PR DESCRIPTION
**Pull request by SalahAdDin**

### CODE REVIEW

**Review by Frezyx — APPROVED** [review]
Nice!
Thank you @SalahAdDin  ❤️

**Comment by Frezyx** [comment]
Please fix analyzer infos and i merge this functionality

**Comment by SalahAdDin** [comment]
> Please fix analyzer infos and i merge this functionality

Donde!

**Comment by SalahAdDin** [comment]
@Frezyx Any plan to release a new version?

**Comment by Frezyx** [comment]
Soon

**Pull request merged**
