### PR TITLE
added ElementGroupButton

### PR DESCRIPTION
**Pull request by andrezanna**
Created class ElementGroupButton to support external edit of the list like in case of reset buttons or similar.

### CODE REVIEW

**Comment by andrezanna** [comment]
https://user-images.githubusercontent.com/27011744/136598269-4622956f-092c-48bf-b3d6-07551d940d6b.mp4

As @Errichamonda pointed I needed more control on these buttons, since i'm using it for a filter page.
I get values saved in shared prefs and can reset externally.
Hope the video attached clears my intention.

**Comment by Frezyx** [comment]
Sorry for answering so late. I didn't see any comments until this moment. This is a good functionality, but I think not everyone needs it. Now I have added a Group Button controller to work with the package logic and am trying to make a button Builder for the new version in order to customize the UI elements.

**Comment by Frezyx** [comment]
@andrezanna 
I will gladly accept your features and changes to the package if you reduce they personality and adjust the code to the current functionality of the package

**Comment by Frezyx** [comment]
@andrezanna  
I want to say that I like the UI of your application. 👍🏻 
 I am very glad if the package could help you achieve your goals at a certain time

**Comment by andrezanna** [comment]
@Frezyx 
Many thanks.
Can you explain me better what you mean by reduce the personality?
I tried to maintan general purpose as your package.

**Pull request closed without merging**
